name: 'Build rp2040 project'
desciption: 'Build rp2040 cmake project with SDK'
author: 'rafaelcorsi'

inputs:
  name:
    description: 'Folder name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: PICO_SDK_PATH=/pico/pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE  -DPICO_TOOL=off ..

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build . --parallel $(nproc) --target ${name}
