name: 'Build rp2040 project'
author: 'rafaelcorsi'

inputs:
  name:
    description: 'Folder name'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up the toolchain
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: checkout code
      uses: actions/checkout@v3

    - name: Checkout pico-sdk
      uses: actions/checkout@v3
      with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk

    - name: Create Build Environment
      shell: bash
      run:  cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: PICO_SDK_PATH=../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DPICO_TOOL=off

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build . --parallel 4 --target "${{ inputs.name }}" 
