name: 'Build rp2040 project'
desciption: 'Build rp2040 cmake project with SDK'
author: 'rafaelcorsi'

runs:
  using: "composite"
  steps:
    - name: Set up the toolchain
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: checkout code
      uses: actions/checkout@v3

    - name: Checkout pico-sdk
      uses: actions/checkout@v3
      with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk

    - name: Checkout pico-sdk submodules
      shell: bash
      working-directory: pico-sdk
      run: git submodule update --init

    - name: Create Build Environment
      shell: bash
      run:  cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: PICO_SDK_PATH=../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Get core count
      shell: bash
      id: core_count
      run : cat /proc/cpuinfo  | grep processor | wc -l

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build . --parallel $(nproc)
