name: 'Build rp2040 project'
desciption: 'Build rp2040 cmake project with SDK'
author: 'rafaelcorsi'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache pico-sdk
      uses: actions/cache@v3
      with:
        path: pico-sdk
        key: ${{ runner.os }}-pico-sdk
        restore-keys: |
          ${{ runner.os }}-pico-sdk

    - name: Checkout pico-sdk (if not cached)
      if: steps.cache-pico-sdk.outputs.cache-hit != 'true'
      uses: actions/checkout@v3
      with:
          repository: raspberrypi/pico-sdk
          path: pico-sdk

    - name: Checkout pico-sdk submodules
      if: steps.cache-pico-sdk.outputs.cache-hit != 'true'
      shell: bash
      working-directory: pico-sdk
      run: git submodule update --init

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential

    - name: Create Build Environment
      shell: bash
      run: cmake -E make_directory build

    - name: Configure CMake
      shell: bash
      working-directory: build
      run: PICO_SDK_PATH=../pico-sdk cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build . --parallel $(nproc)
